### PR TITLE
add Ucorrection flag, not pretty

### PR DESCRIPTION
**Pull request by agurvich**
Hopefully you can get what you need from this-- these are the copies of randspectra and spectra that are from my (ancient) version of fake_spectra. I'm not sure what sort of compatibility they have with the current code base (nor am I sure if I changed anything in `spb_common`, or if you have...). 

In some perfect world I would've maintained my pipeline as you updated your library... This is also from a period of my life where I was very unfamiliar with git-- so it might even have changes you yourself put in during the REU (but that I then copied and pasted into my frozen copy). 

Sorry to be trying to pull into master, I'm not sure if there's another branch you'd rather I make the PR for.

### CODE REVIEW

**Comment by sbird** [comment]
Thanks Alex! No worries, I can figure it out.

**Comment by sbird** [comment]
Turns out after consultation that this isn't necessary any more - the updated internalenergies have been added to the TNG snapshots, so we're fine.

**Comment by agurvich** [comment]
Haha, no way! All that effort for nothing. Well, thanks for letting me know.

**Comment by sbird** [comment]
I actually completed the forward port before Dylan pointed out it's discussed in the TNG paper: 1812.05609.  Oh well! Thanks for the PR anyway.

**Pull request closed without merging**
