### PR TITLE
Added gamma_factor and temp_factor as options in RateNetworkSpectra

### PR DESCRIPTION
**Pull request by andreufont**
This addresses issue #44 

I tested that I can generate spectra with these options, and that they provide different mean flux, but I haven't fully tested the resulting value of (T_0,gamma) since I only have a small test simulation in my laptop.

### CODE REVIEW

**Comment by andreufont** [comment]
I've also added the option to pass treecool_file, hubble and fbar options to the network.

**Comment by sbird** [comment]
Thanks, looks good to me! I think you are indeed the first one to rescale gamma with the rate network (we have used RateNetworkSpectra mostly for DLAs).

**Comment by sbird** [comment]
Wait, sorry, I merge too quickly. You can just pass the temp_factor and gamma_factor in the gasprop_args dictionary, can't you? It is intended that to avoid a million arguments to the RateNetworkSpectra you pass a gasprop_args dictionary containing the arguments for the gas properties structure (which does not have to be one of the structures implemented so far).

**Comment by andreufont** [comment]
Hi @sbird - yes, you need to add both factors to the gasprop_args, but this is not an input of RateNetworkSpectra either. 

One option is to make gasprop_args an input of RateNetworkSpectra, the other option was to do what I did. I don't mind either way.

**Comment by sbird** [comment]
Ah, indeed. I see. The gasprop_args is over-ridden by the constructor. Got it. In that case, let's leave is as is, fully merged because the revert is a bit painful :-) Thanks!

**Comment by andreufont** [comment]
Great. Thanks!

**Pull request merged**
