### PR TITLE
Namespace cleanup

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by rainwoodman** [comment]
- Changed all imports to relative imports;
- all modules moved into fake_spectra name space.
- Added runtests.py for driving tests. It all passed on my python 3.5.
- I didn't touch .travis.yml; failure due to that.
- Makefile tries to build a python package. looking strange.

**Comment by sbird** [comment]
Thanks - this will break downstream analysis scripts in fact, but I will fix them.

**Comment by sbird** [comment]
What is the runtests package? Why use that instead of nosetests?

**Comment by rainwoodman** [comment]
It actually rebuilds the package & installs it to a temp location before running the tests. so you don't have do deal with that 'developer' mode and in-place builds any more.

**Comment by sbird** [comment]
Oh, neat. Do I still need nose installed?

**Comment by sbird** [comment]
It does not seem to build the C module anymore. Do you know why?

**Comment by rainwoodman** [comment]
It did build on my system. try to remove the build directory? This is how it outputs when it worked.

```
(root) [yfeng1@waterfall fake_spectra]$ python runtests.py
Purging /home/yfeng1/source/fake_spectra/build/testenv ...
Purging /home/yfeng1/source/fake_spectra/build/test ...
Building, see build.log...
Build OK
============================================================================ test session starts ============================================================================
platform linux -- Python 3.5.2, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/yfeng1/source/fake_spectra, inifile:
plugins: profiling-1.2.6
collected 9 items 

../testenv/lib/python3.5/site-packages/fake_spectra/tests/test_spectra.py .
../testenv/lib/python3.5/site-packages/fake_spectra/tests/test_statistics.py ....
../testenv/lib/python3.5/site-packages/fake_spectra/tests/test_spectra.py ....           

========================================================================= 9 passed in 13.63 seconds =========================================================================
(root) [yfeng1@waterfall fake_spectra]$ cat build.log
running build
running build_py
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/get_python_libdir.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/line_data.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/_np_setup.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/spec_utils.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/unitsystem.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/__init__.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/lab.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/voigtfit.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/spectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/abstractsnapshot.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/emission.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/fluxstatistics.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/gas_properties.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/griddedspectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/haloassigned_spectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/halospectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/plot_spectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/randspectra.py -> build/lib.linux-x86_64-3.5/fake_spectra
creating build/lib.linux-x86_64-3.5/fake_spectra/tests
copying fake_spectra/tests/__init__.py -> build/lib.linux-x86_64-3.5/fake_spectra/tests
copying fake_spectra/tests/test_statistics.py -> build/lib.linux-x86_64-3.5/fake_spectra/tests
copying fake_spectra/tests/test_spectra.py -> build/lib.linux-x86_64-3.5/fake_spectra/tests
copying fake_spectra/atom.dat -> build/lib.linux-x86_64-3.5/fake_spectra
copying fake_spectra/tests/example_civ_tau.npz -> build/lib.linux-x86_64-3.5/fake_spectra/tests
running build_ext
building 'fake_spectra._spectra_priv' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/fake_spectra
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifake_spectra/ -I/home/yfeng1/anaconda3/install/lib/python3.5/site-packages/numpy/core/include -I/home/yfeng1/anaconda3/install/include/python3.5m -c fake_spectra/py_module.cpp -o build/temp.linux-x86_64-3.5/fake_spectra/py_module.o -ffast-math -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifake_spectra/ -I/home/yfeng1/anaconda3/install/lib/python3.5/site-packages/numpy/core/include -I/home/yfeng1/anaconda3/install/include/python3.5m -c fake_spectra/absorption.cpp -o build/temp.linux-x86_64-3.5/fake_spectra/absorption.o -ffast-math -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifake_spectra/ -I/home/yfeng1/anaconda3/install/lib/python3.5/site-packages/numpy/core/include -I/home/yfeng1/anaconda3/install/include/python3.5m -c fake_spectra/index_table.cpp -o build/temp.linux-x86_64-3.5/fake_spectra/index_table.o -ffast-math -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifake_spectra/ -I/home/yfeng1/anaconda3/install/lib/python3.5/site-packages/numpy/core/include -I/home/yfeng1/anaconda3/install/include/python3.5m -c fake_spectra/Faddeeva.cpp -o build/temp.linux-x86_64-3.5/fake_spectra/Faddeeva.o -ffast-math -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ifake_spectra/ -I/home/yfeng1/anaconda3/install/lib/python3.5/site-packages/numpy/core/include -I/home/yfeng1/anaconda3/install/include/python3.5m -c fake_spectra/part_int.cpp -o build/temp.linux-x86_64-3.5/fake_spectra/part_int.o -ffast-math -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -L/home/yfeng1/anaconda3/install/lib -Wl,-rpath=/home/yfeng1/anaconda3/install/lib,--no-as-needed build/temp.linux-x86_64-3.5/fake_spectra/py_module.o build/temp.linux-x86_64-3.5/fake_spectra/absorption.o build/temp.linux-x86_64-3.5/fake_spectra/index_table.o build/temp.linux-x86_64-3.5/fake_spectra/Faddeeva.o build/temp.linux-x86_64-3.5/fake_spectra/part_int.o -L/home/yfeng1/anaconda3/install/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/fake_spectra/_spectra_priv.cpython-35m-x86_64-linux-gnu.so -ffast-math -lgomp
running install
running install_lib
creating /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages
creating /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/get_python_libdir.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/line_data.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/_np_setup.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/spec_utils.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/unitsystem.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/__init__.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/lab.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/voigtfit.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/spectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/abstractsnapshot.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/emission.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/fluxstatistics.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/gas_properties.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/griddedspectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/haloassigned_spectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/halospectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/plot_spectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/randspectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
creating /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests
copying build/lib.linux-x86_64-3.5/fake_spectra/tests/__init__.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests
copying build/lib.linux-x86_64-3.5/fake_spectra/tests/test_statistics.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests
copying build/lib.linux-x86_64-3.5/fake_spectra/tests/test_spectra.py -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests
copying build/lib.linux-x86_64-3.5/fake_spectra/tests/example_civ_tau.npz -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests
copying build/lib.linux-x86_64-3.5/fake_spectra/atom.dat -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
copying build/lib.linux-x86_64-3.5/fake_spectra/_spectra_priv.cpython-35m-x86_64-linux-gnu.so -> /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/get_python_libdir.py to get_python_libdir.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/line_data.py to line_data.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/_np_setup.py to _np_setup.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/spec_utils.py to spec_utils.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/unitsystem.py to unitsystem.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/lab.py to lab.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/voigtfit.py to voigtfit.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/spectra.py to spectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/abstractsnapshot.py to abstractsnapshot.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/emission.py to emission.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/fluxstatistics.py to fluxstatistics.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/gas_properties.py to gas_properties.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/griddedspectra.py to griddedspectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/haloassigned_spectra.py to haloassigned_spectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/halospectra.py to halospectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/plot_spectra.py to plot_spectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/randspectra.py to randspectra.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests/test_statistics.py to test_statistics.cpython-35.pyc
byte-compiling /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra/tests/test_spectra.py to test_spectra.cpython-35.pyc
running install_egg_info
Writing /home/yfeng1/source/fake_spectra/build/testenv/lib/python3.5/site-packages/fake_spectra-1.0.2a-py3.5.egg-info
```

**Comment by rainwoodman** [comment]
runtests uses pytest; so I think you don't need nose installed. but numpy pulls in nose anyways.

**Comment by sbird** [comment]
Thanks! That was it.

**Comment by rainwoodman** [comment]
I think the dependency rules on the header files are not added. That could be why it is not building after touch the header files.

**Pull request merged**
