### PR TITLE
Areporoundofffix

### PR DESCRIPTION
**Pull request by sbird**
A few cleanups and a work-around for the floating point problems we have been experiencing with big simulations.

### CODE REVIEW

**Comment by xiaohanzai** [comment]
Some minor issues: I guess line 201 and 151 in absorption.cpp need to be changed as well, because arr2 is not initialized with <0 values anymore. Or perhaps we could change line 220 and 164? Such that when z > 2 x nbins we skip the calculation for that particle.

**Comment by sbird** [comment]
Nicely caught, thanks! dr2 < 0 actually could have had fp roundoff from index_table.cpp, line 218 so this is I think the better fix.

**Comment by xiaohanzai** [comment]
Great! This works very well. Produces the same spectra as the previous implementation. Thanks a lot :-)

**Comment by sbird** [comment]
Perfect! Thank you for the original code and for contributing!

**Pull request merged**
