### PR TITLE
adding get_curvature function

### PR DESCRIPTION
**Pull request by mafern**
Add a function that calculate the curvature for sightlines and the sub functions required therein:

- spline_fit (fits the flux for each sightline passed using a chi^2 criteria and minimum resolution)
- renormalize_flux (chops the flux into sections, normalizes by the max in each section)
- compute_curvature (computes the curvature -- can be used without the previous steps for noiseless spectra, if rescaling is not desired)

Also, some minor changes to existing functions.

### CODE REVIEW

**Comment by sbird** [comment]
I reviewed for python language problems, not physics, and it looks fine to me. Could you please add a newline at the end of the file? Please also run pylint on spectra.py and fix any reasonable issues in the new code (unreasonable issues are naming and suggestions about enumerate). Then I will merge it.

**Comment by mafern** [comment]
Newline added and code cleaned up a bit -- only pylint suggestion that came up that is still worth resolving is:

_fake_spectra/spectra.py:35:0: E0401: Unable to import 'fake_spectra._spectra_priv' (import-error)_

**Comment by sbird** [comment]
That one is not important - pylint doesn't really understand C modules and throws that error spuriously.

**Comment by sbird** [comment]
Merging, thank you!

**Pull request merged**
